### ISSUE TITLE
ERROR! 401 { error: 'Not logged in', success: false }

### ISSUE THREAD

**Issue by sidmish** [askmike/ftx-api-rest#3]
I am running the sample.js file with putting my key and secret but unfortunately i am receiving the following erroe:
`ERROR! 401 { error: 'Not logged in', success: false }
(node:21804) UnhandledPromiseRejectionWarning: Error: Not logged in
    at IncomingMessage.<anonymous> (C:\Users\siddh\Desktop\FTX\ftx-api-rest\index.js:130:27)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:21804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by askmike** [comment]
That's FTX way of telling you there is a problem with the API key

**Comment by askmike** [comment]
That error is response coming straight from FTX, as such not much this library can do with or about it. I am closing this (as it's not an issue with this project) but if the issue persists feel free to provide additional information here.
