### ISSUE TITLE
Add parameter to /positions request

### ISSUE THREAD

**Issue by Argon007** [askmike/ftx-api-rest#4]
Hello,

With the "Get Positions" request I want to add the "showAvgPrice" parameter (https://docs.ftx.com/?javascript#get-positions)
I tried this but it doesn't work:

```
ftx.request({
    method: 'GET',
    path: '/positions',
    data: 'showAvgPrice=true'
}).then(console.log);
```

Thanks!

**Comment by Argon007** [comment]
Found it:
```
ftx.request({
    method: 'GET',
    path: '/positions',
    data: {'showAvgPrice': 'True'}
}).then(console.log);
```

**Comment by askmike** [comment]
while that might work, probably better to do:

    data: {'showAvgPrice': true}
